# pref_dialog.py
"""
Preferences dialog for configuring connections and AGWPE settings.

This module defines the `PrefDialog` class, a Qt dialog that loads values from
the INI-backed `appconfig`, populates the UI, and writes user changes back to
the INI file when accepted.

Functions
---------
clean_up_cds(input_string)
    Normalize a comma-delimited string by trimming whitespace around each token.
to_bool(value)
    Interpret common truthy/falsey strings and values as a Python boolean.

Classes
-------
PrefDialog(QDialog, Ui_prefDialog)
    The preferences dialog implementation that binds UI widgets to settings.
"""
# ---------------------------------------------------------------------
# Field Map: INI <-> Preferences Dialog Widgets
#
# Serial Section [serial]
#   port        <-> cboComPort
#   baudrate    <-> cboBaudRate
#   databits    <-> cboDataBits
#   stopbits    <-> cboStopBits
#   parity      <-> cboParity
#   flowcontrol <-> cboFlowControl
#
# TCP / Telnet Section [tcp]
#   host        <-> lineEditTelnetHost
#   port        <-> lineEditTelnetPort
#   timeout     <-> lineEditTelnetTimeout
#
# SSH Section [ssh]
#   required    <-> checkBoxSshReq
#   login       <-> lineEditSshLogin
#   password    <-> lineEditSshPassword
#
# AGWPE Section [agwpe]
#   host        <-> lineEditAgwpeHost
#   port        <-> lineEditAgwpePort
#   timeout     <-> lineEditAgwpeTimeout
#   fmcall      <-> lineEditAgwpeFmCall
#   logonreq    <-> checkBoxAgwpeLogonReq
#   username    <-> lineEditAgwpeUserName
#   password    <-> lineEditAgwpePassword
#   mode        <-> radioButtonAgwpeBbsMode / radioButtonAgwpeUnprotoMode
#
# AGWPE-BBS Section [agwpe-bbs]
#   tocall      <-> lineEditAgwpeToCall
#   via         <-> lineEditAgwpeBbsVia
#   connect     <-> radioButtonAgwpeBbsDirect / radioButtonAgwpeBbsDigipeat
#
# AGWPE-Unproto Section [agwpe-unproto]
#   unprotoid   <-> lineEditAgwpeUnprotoId
#   via         <-> lineEditAgwpeUnprotoVia
#   connect     <-> radioButtonAgwpeUnprotoDirect / radioButtonAgwpeUnprotoDigipeat
#
# ---------------------------------------------------------------------

from PySide6.QtSerialPort import QSerialPortInfo
import sys

# 260522: migrate from PyQt5 to PySide6    
from PySide6.QtWidgets import QDialog
from PySide6.QtGui import QIcon

from services.app_info import AppInfo
from services.app_paths import AppPaths

from views.pref_dialog_view import Ui_prefDialog   # generated by pyuic5
from config.appconfig import appconfig

def clean_up_cds(input_string):
    """
    Normalize a comma-delimited string by trimming whitespace.
    Removes leading & trailing spaces from each element in a comma-delimited string.

    Parameters
    ----------
    input_string : str or None
        Input string with comma-delimited tokens, or None.

    Returns
    -------
    str
        A comma-joined string with each token stripped of leading/trailing
        whitespace. Returns '' if `input_string` is None.
    """
    # Split the string by commas
    if input_string is not None:
        items = input_string.split(',')                # put sting elements in a list
        item_list = [item.strip() for item in items]   # Strip whitespace from each item, store in a list
        cleaned_string = ','.join(item_list)           # put it back into a string
    else:
        cleaned_string = ''
    return cleaned_string


def to_bool(value):
    """
    Best-effort conversion of various truthy/falsey forms to bool.

    Notes
    -----
    `bool("False")` is True in Python because non-empty strings are truthy.
    This helper interprets common string forms instead.

    Behaviors
    ---------
    Makes False, 0, No, etc. become actual boolean.
    bool() doesn’t convert strings like "False" the way you expect;  only checks if the string is empty or not.


    Parameters
    ----------
    value : Any
        Value to interpret as boolean. Strings like "true", "yes", "on", "1"
        (case-insensitive) are treated as True; "false", "no", "off", "0"
        are treated as False. Booleans are returned unchanged.

    Returns
    -------
    bool
        Interpreted boolean value.
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in ("1", "true", "yes", "on")
    return bool(value)


# #189, mirrors #176 for OutpostX
# outside of the class
def list_serial_ports() -> list[str]:
    """
    Return serial ports currently recognized by the operating system.

        Depending on the platform, this will return (example):
        Windows:   COM3
        Linux:     /dev/ttyUSB0
        macOS:     /dev/cu.... or /dev/tty....
    """
    ports: list[str] = []

    for info in QSerialPortInfo.availablePorts():

        # --- Windows handler ---
        if sys.platform.startswith("win"):
            port = info.portName().strip()

        # --- Linux handler ---
        elif sys.platform.startswith("linux"):
            # Linux may expose many legacy ttyS devices even when
            # no corresponding serial hardware is actually present.
            has_identity = (
                bool(info.description().strip())
                or bool(info.manufacturer().strip())
                or bool(info.serialNumber().strip())
                or info.hasVendorIdentifier()
                or info.hasProductIdentifier()
            )

            if not has_identity:
                continue

            port = info.systemLocation().strip()

        # --- Mac OS handler ---
        elif sys.platform.startswith("darwin"):
            port = info.systemLocation().strip()

            # macOS exposes both call-out (/dev/cu.*) and call-in
            # (/dev/tty.*) devices.  OutpostX initiates the serial
            # connection, so present the call-out devices.
            if not port.startswith("/dev/cu."):
                continue

        else:
            port = info.systemLocation().strip()

        if port:
            ports.append(port)

    return sorted(set(ports))



class PrefDialog(QDialog, Ui_prefDialog):
    """
    Preferences dialog for application configuration.

    Responsibilities
    ----------------
    - Load values from the INI file via `appconfig` on construction.
    - Populate widgets (serial, TCP/Telnet, SSH, AGWPE) from loaded values.
    - On acceptance, persist updated values back to the INI file.

    Notes
    -----
    - INI values are stored as strings; fields that represent booleans
      must be normalized before assigning to checkbox states.
    - `clean_up_cds` is used for multi-hop "via" lists to ensure consistent
      comma-delimited formatting.
    - Using `bool("False")` will evaluate to True because any non-empty
      string is truthy in Python.
    
    Example
    -------
    >>> iniAgwpeUnproto = config.get('agwpe', 'unproto')
    >>> self.checkBoxAgwpeUnproto.setChecked(to_bool(iniAgwpeUnproto))
    """

    def __init__(self, ini, parent=None):
        """
        Initialize the dialog and wire signals.

        Parameters
        ----------
        parent : QWidget or None
                Parent widget, if any.
        """
        super().__init__(parent)
        self.setupUi(self)               # sets up all widgets from the .ui file (REQUIRED)
        self.ini = ini                   # reference to the SAME object

        self.setWindowTitle(f"{AppInfo.TITLE} Preferences")
        self.setWindowIcon(QIcon(AppPaths.app_icon()))

        self._load_settings()            # self.settings = settings or {}

        # connect signals to slots
        self.buttonBox.accepted.connect(self._on_accept)
        self.buttonBox.rejected.connect(self.reject)


    def _load_settings(self):
        """
        Populate dialog widgets from INI values.

        This method reads configuration values for Serial, TCP/Telnet, SSH,
        and AGWPE (including BBS and Unproto sub-sections) and sets the
        corresponding UI controls. It also enumerates available serial ports.
        """
        # Example: if your UI has a QLineEdit called lineEditHost
        self.lineEditTelnetHost.setText(self.ini.get('telnet', 'host'))
        self.lineEditTelnetPort.setText(self.ini.get('telnet', 'port'))

        ininame = self.ini.get('serial', 'name')
        iniport = self.ini.get('serial', 'port')
        inibaud = self.ini.get('serial', 'baudrate')
        inidata = self.ini.get('serial', 'databits')
        inistop = self.ini.get('serial', 'stopbits')
        iniparity = self.ini.get('serial', 'parity')
        iniflowControl = self.ini.get('serial', 'flowControl')

        # Set up Com Port / Serial Config
        self.lineEditSerialName.setText(ininame)

        # self.cboComPort.addItem("COM3")
        self.cboComPort.clear()
        self._load_com_ports()
        self.cboComPort.setCurrentText(iniport)

        self.cboBaudRate.clear()
        items_list = ["110","300","600","1200","2400","4800","9600","14400",
                     "19200","28800","38400","56000","57600","115200","128000","256000"]
        self.cboBaudRate.addItems(items_list)
        self.cboBaudRate.setCurrentText(inibaud)

        items_list = ["4", "5", "6", "7", "8"]
        self.cboDataBits.addItems(items_list)
        self.cboDataBits.setCurrentText(inidata)

        items_list = ["1", "1.5", "2"]
        self.cboStopBits.addItems(items_list)
        self.cboStopBits.setCurrentText(inistop)

        items_list = ["Even", "Odd", "None", "Mark", "Space"]
        self.cboParity.addItems(items_list)
        self.cboParity.setCurrentText(iniparity)

        items_list = ["None", "RTS/CTS", "XON/XOFF"]
        self.cboFlowControl.addItems(items_list)
        self.cboFlowControl.setCurrentText(iniflowControl)

        # Set the telnet / raw tcp fields
        inihost = self.ini.get('tcp', 'host')
        iniport = self.ini.get('tcp', 'port')
        initimeout = self.ini.get('tcp', 'timeout')
        inisshreq = self.ini.get('ssh', 'required')
        inilogin = self.ini.get('ssh', 'login')
        inipassword = self.ini.get('ssh', 'password')

        self.lineEditTelnetHost.setText(inihost)
        self.lineEditTelnetPort.setText(iniport)
        self.lineEditTelnetTimeout.setText(initimeout)
        self.checkBoxSshReq.setChecked(to_bool(inisshreq))
        self.lineEditSshLogin.setText(inilogin)
        self.lineEditSshPassword.setText(inipassword)

        # Agwpe-Access Menu
        iniAgwpeHost = self.ini.get('agwpe', 'host')
        iniAgwpePort = self.ini.get('agwpe', 'port')
        iniAgwpeTimeout = self.ini.get('agwpe', 'timeout')
        iniAgwpeFmCall = self.ini.get('agwpe', 'fmcall')
        iniAgwpeLogonReq = self.ini.get('agwpe', 'logonreq')
        iniAgwpeUserName = self.ini.get('agwpe', 'username')
        iniAgwpePassword = self.ini.get('agwpe', 'password')

        if self.ini.get('agwpe', 'mode') == 'Bbs':
           self.radioButtonAgwpeBbsMode.setChecked(True)
        else:
           self.radioButtonAgwpeUnprotoMode.setChecked(True) 

        # Agwpe-Bbs Menu
        iniAgwpeToCall = self.ini.get('agwpe-bbs', 'tocall')
        iniAgwpeBbsVia = self.ini.get('agwpe-bbs', 'via')

        if self.ini.get('agwpe-bbs', 'connect') == 'Direct':
           self.radioButtonAgwpeBbsDirect.setChecked(True)      # Direct
        else:
           self.radioButtonAgwpeBbsDigipeat.setChecked(True)    # Digipeat

        # Agwpe-Unproto Menu
        iniAgwpeUnprotoId = self.ini.get('agwpe-unproto', 'unprotoid')
        iniAgwpeUnprotoVia = self.ini.get('agwpe-unproto', 'via')

        if self.ini.get('agwpe-unproto', 'connect') == 'Direct':
           self.radioButtonAgwpeUnprotoDirect.setChecked(True)      # Direct
        else:
           self.radioButtonAgwpeUnprotoDigipeat.setChecked(True)    # Digipeat

        # Agwpe-Access Menu
        self.lineEditAgwpeHost.setText(iniAgwpeHost)
        self.lineEditAgwpePort.setText(iniAgwpePort)
        self.lineEditAgwpeTimeout.setText(iniAgwpeTimeout)
        self.lineEditAgwpeFmCall.setText(iniAgwpeFmCall)
        self.checkBoxAgwpeLogonReq.setChecked(to_bool(iniAgwpeLogonReq))
        self.lineEditAgwpeUserName.setText(iniAgwpeUserName)
        self.lineEditAgwpePassword.setText(iniAgwpePassword)

        # Agwpe-Bbs Menu
        self.lineEditAgwpeBbsVia.setText(clean_up_cds(iniAgwpeBbsVia))
        self.lineEditAgwpeToCall.setText(iniAgwpeToCall)

        # Agwpe-Unproto Menu
        self.lineEditAgwpeUnprotoVia.setText(clean_up_cds(iniAgwpeUnprotoVia))
        self.lineEditAgwpeUnprotoId.setText(clean_up_cds(iniAgwpeUnprotoId))

        self.tabWidget.setCurrentIndex(0)        # open to tab #0 Serial

    def _load_com_ports(self):
        """
        Populate the Serial Port combo box with currently available
        external serial devices appropriate for OpTermX use.
        """
        # #189, mirrors #176 for OutpostX
        ports = list_serial_ports()

        if ports:
            self.cboComPort.addItems(ports)
        else:
            self.cboComPort.addItem("NONE")

    def _on_accept(self):
        """
        Gather values from widgets and persist them back to the INI file.

        This method reads all current UI control values (Serial, TCP/Telnet,
        SSH, AGWPE, BBS, Unproto), writes them to the `appconfig` instance,
        and saves the configuration to disk.
        """
        # ini.set('serial', 'port', port)
        # 189, only load actual ports.  If none, save as blank.
        serial_port = self.cboComPort.currentText().strip()

        if serial_port == "NONE":
            serial_port = ""

        self.ini.set('serial', 'port', serial_port)
        self.ini.set('serial', 'baudrate', self.cboBaudRate.currentText())
        self.ini.set('serial', 'databits', self.cboDataBits.currentText())
        self.ini.set('serial', 'stopbits', self.cboStopBits.currentText())
        self.ini.set('serial', 'parity', self.cboParity.currentText())
        self.ini.set('serial', 'flowcontrol', self.cboFlowControl.currentText())

        self.ini.set('tcp', 'host', self.lineEditTelnetHost.text())
        self.ini.set('tcp', 'port', self.lineEditTelnetPort.text())
        self.ini.set('tcp', 'timeout', self.lineEditTelnetTimeout.text())
        self.ini.set('ssh', 'required', self.checkBoxSshReq.isChecked())
        self.ini.set('ssh', 'login', self.lineEditSshLogin.text())
        self.ini.set('ssh', 'password', self.lineEditSshPassword.text())

        # Agwpe-Access Menu
        self.ini.set('agwpe', 'host', self.lineEditAgwpeHost.text())
        self.ini.set('agwpe', 'port', self.lineEditAgwpePort.text())
        self.ini.set('agwpe', 'timeout', self.lineEditAgwpeTimeout.text())
        self.ini.set('agwpe', 'fmcall', self.lineEditAgwpeFmCall.text().upper())
        self.ini.set('agwpe', 'logonreq', self.checkBoxAgwpeLogonReq.isChecked())
        self.ini.set('agwpe', 'username', self.lineEditAgwpeUserName.text())
        self.ini.set('agwpe', 'password', self.lineEditAgwpePassword.text())

        if self.radioButtonAgwpeBbsMode.isChecked():
           self.ini.set('agwpe', 'mode', 'Bbs')      
        else:
           self.ini.set('agwpe', 'mode', 'Unproto')   

        # Agwpe-Bbs Menu
        self.ini.set('agwpe-bbs', 'tocall', self.lineEditAgwpeToCall.text().upper())
        self.ini.set('agwpe-bbs', 'via', self.lineEditAgwpeBbsVia.text().upper())

        if self.radioButtonAgwpeBbsDirect.isChecked():
           self.ini.set('agwpe-bbs', 'connect', 'Direct')      # Direct
        else:
           self.ini.set('agwpe-bbs', 'connect', 'Digipeat')    # Digipeat

        # Agwpe-Unproto Menu
        self.ini.set('agwpe-unproto', 'unprotoid', self.lineEditAgwpeUnprotoId.text().upper())
        self.ini.set('agwpe-unproto', 'via', self.lineEditAgwpeUnprotoVia.text().upper())

        if self.radioButtonAgwpeUnprotoDirect.isChecked():
           self.ini.set('agwpe-unproto', 'connect', 'Direct')      # Direct
        else:
           self.ini.set('agwpe-unproto', 'connect', 'Digipeat')    # Digipeat

        self.ini.save()

        # close this dialog and return QDialog.Accepted to whoever called exec()
        super().accept()
