# ui/station_settings_widget.py
from __future__ import annotations

from typing import Optional

from PySide6 import QtWidgets, QtCore, QtGui

from data.station_profile_model import StationProfile


class StationSettingsWidget(QtWidgets.QWidget):
    """Detail editor for a single StationProfile.

    Signals
    -------
    changed : emitted whenever a field changes (for dirty tracking in SetupDialog).

    Behavior
    --------
    * legal_call_sign is normalized to uppercase and validated with ^[A-Za-z0-9/]+$.
    * msg_id_prefix is normalized to uppercase, max 3 chars, [A-Za-z0-9].
    * msg_id_prefix auto-follows the last 3 characters of the call **until**
      the user edits the prefix field (then it's considered custom).
    * signature is optional multi-line text stored as-is.
    """

    changed = QtCore.Signal()

    def __init__(self, parent: Optional[QtWidgets.QWidget] = None) -> None:
        super().__init__(parent)

        self._building = False
        self._current: Optional[StationProfile] = None

        # Tracks whether prefix is still auto-generated
        self._prefix_autogenerated = True
        self._last_call_for_prefix = ""

        # ------------------------------------------------------------------
        # Layout
        # ------------------------------------------------------------------
        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(8, 8, 8, 8)
        root.setSpacing(8)

        # --- NEW GROUP BOX FOR TOP THREE FIELDS ---------------------------
        grp_main = QtWidgets.QGroupBox("Station ID")
        grp_main.setStyleSheet("QGroupBox { font-weight: bold; }")     # makes label BOLD

        main_layout = QtWidgets.QFormLayout(grp_main)
        main_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        root.addWidget(grp_main)

        # Replace the old "form" with the new "main_layout"
        form = main_layout

        self.edCall = QtWidgets.QLineEdit()
        self.edName = QtWidgets.QLineEdit()
        self.edPrefix = QtWidgets.QLineEdit()

        form.addRow("User Call Sign *:", self.edCall)
        form.addRow("User Name *:", self.edName)
        form.addRow("Message ID Prefix *:", self.edPrefix)

        # Signature group (unchanged)
        grp_sig = QtWidgets.QGroupBox("Signature")
        sig_layout = QtWidgets.QVBoxLayout(grp_sig)

        self.txtSignature = QtWidgets.QPlainTextEdit()
        self.txtSignature.setMinimumHeight(80)
        self.txtSignature.setMaximumHeight(120)
        sig_layout.addWidget(self.txtSignature)

        # #176, 260901
        required_note = QtWidgets.QLabel("* Required field")
        required_note.setStyleSheet("font-style: italic;")
        root.addWidget(required_note)

        # Prevent group box from stretching vertically
        policy = grp_sig.sizePolicy()
        policy.setVerticalPolicy(QtWidgets.QSizePolicy.Fixed)
        grp_sig.setSizePolicy(policy)

        root.addWidget(grp_sig)
        root.addStretch(1)


        # Validators – allow upper/lower while typing; normalize on focus-out
        call_re = QtCore.QRegularExpression(r"^[A-Za-z0-9/]+$")
        self._call_validator = QtGui.QRegularExpressionValidator(call_re, self)
        self.edCall.setValidator(self._call_validator)

        prefix_re = QtCore.QRegularExpression(r"^[A-Za-z0-9]{0,3}$")
        self._prefix_validator = QtGui.QRegularExpressionValidator(prefix_re, self)
        self.edPrefix.setValidator(self._prefix_validator)

        # Signals → change tracking
        self.edCall.textChanged.connect(self._on_call_changed)
        self.edName.textChanged.connect(self._on_any_changed)
        self.edPrefix.textChanged.connect(self._on_prefix_changed)
        self.txtSignature.textChanged.connect(self._on_any_changed)

        # Normalize to uppercase on editingFinished
        self.edCall.editingFinished.connect(self._normalize_call)
        self.edPrefix.editingFinished.connect(self._normalize_prefix)

    # ------------------------------------------------------------------
    # Load / Save
    # ------------------------------------------------------------------
    def load_profile(self, profile: Optional[StationProfile]) -> None:
        """Populate fields from the given profile (or clear for None)."""
        self._building = True
        try:
            self._current = profile
            if profile is None:
                self.edCall.clear()
                self.edName.clear()
                self.edPrefix.clear()
                self.txtSignature.clear()
                self._prefix_autogenerated = True
                self._last_call_for_prefix = ""
            else:
                call = (profile.legal_call_sign or "").upper()
                name = profile.user_name or ""
                prefix = (profile.msg_id_prefix or "").upper()
                signature = profile.signature or ""

                self.edCall.setText(call)
                self.edName.setText(name)
                self.edPrefix.setText(prefix)
                self.txtSignature.setPlainText(signature)

                auto = call[-3:] if len(call) >= 3 else call
                if prefix == auto:
                    self._prefix_autogenerated = True
                else:
                    self._prefix_autogenerated = False
                self._last_call_for_prefix = call
        finally:
            self._building = False
        # Let SetupDialog decide about dirty flag; emit no changed here.

    def apply_to_profile(self, profile: Optional[StationProfile]) -> StationProfile:
        """Apply current UI values to the given profile (or a new one).

        Does **not** persist to the DB; SetupDialog calls repository.save().
        """
        if profile is None:
            profile = StationProfile()

        call = (self.edCall.text() or "").upper().strip()
        name = (self.edName.text() or "").strip()
        prefix = (self.edPrefix.text() or "").upper().strip()
        signature = self.txtSignature.toPlainText() or ""

        # Enforce max length for prefix here as well, just in case
        if len(prefix) > 3:
            prefix = prefix[:3]

        profile.legal_call_sign = call
        profile.user_name = name
        profile.msg_id_prefix = prefix
        profile.signature = signature

        return profile

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------
    def validate_required_fields(self) -> list[str]:
        """Return the names of required Station ID fields that are blank."""
        missing: list[str] = []

        if not self.edCall.text().strip():
            missing.append("User Call Sign")

        if not self.edName.text().strip():
            missing.append("User Name")

        if not self.edPrefix.text().strip():
            missing.append("Message ID Prefix")

        return missing

    # ------------------------------------------------------------------
    # Change / auto-prefix handling
    # ------------------------------------------------------------------
    def _on_any_changed(self) -> None:
        if self._building:
            return
        self.changed.emit()

    def _on_call_changed(self, text: str) -> None:
        if self._building:
            return

        text = (text or "").upper()
        # Auto-prefix logic
        if self._prefix_autogenerated:
            old_call = self._last_call_for_prefix
            old_auto = old_call[-3:] if len(old_call) >= 3 else old_call
            current_prefix = (self.edPrefix.text() or "").upper()

            # Only update if prefix still matches the previous auto value
            if current_prefix == old_auto:
                new_auto = text[-3:] if len(text) >= 3 else text
                self._building = True
                try:
                    self.edPrefix.setText(new_auto)
                finally:
                    self._building = False

        self._last_call_for_prefix = text
        self.changed.emit()

    def _on_prefix_changed(self, _text: str) -> None:
        if self._building:
            return
        # User touched prefix → treat as customized from now on
        self._prefix_autogenerated = False
        self.changed.emit()

    def _normalize_call(self) -> None:
        if self._building:
            return
        txt = (self.edCall.text() or "").upper().strip()
        self._building = True
        try:
            self.edCall.setText(txt)
        finally:
            self._building = False

    def _normalize_prefix(self) -> None:
        if self._building:
            return
        txt = (self.edPrefix.text() or "").upper().strip()
        if len(txt) > 3:
            txt = txt[:3]
        self._building = True
        try:
            self.edPrefix.setText(txt)
        finally:
            self._building = False
